language: python            # this works for Linux but is an error on macOS or Windows
if: tag IS blank
jobs:
  include:

    - name: "Python 3.x.x on macOS"
      os: osx
      osx_image: xcode12.5  # Python 3.x.x running on macOS 11.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      script:
        - pip3 install -r requirements_mac.txt
        - sh build.sh
        - shasum -a 256 "dist/Cyber-Essentials-at-Home.pkg"
      deploy:
        provider: releases
        api_key:
          secure: CvaeWnw10kKCkTNHm9E208exwfn5S6pluVQ2yabWgTJo/wZdEFhx+nC5KbodetuNslwDafStDg2i8E7Yl2dtZgzRA83EWfzVlWzfqF4bYYyoF1kVpdhjPOVWIrqqymBqrOH4HIrGgEyzB67imh3WI27xEmY+q+u2sTIzXA4xzbai71wo1w1wVqSbag0+0j4CunhaoR175IssxtH3RPPHe9XKKY65HZMqJsgdWAAy/NvbKOSGAG35vkJTDB7ESQh3DNRNB0yWo1YkOOQKOkP6od+u/Gm60Nr3E7vPfxCMwE9h1wACi2vDLBtscROLSJdEf2tmhzliYK+H3aMpUGwiFOAXXJmrc4oQWDnlQQWndyFWqbuj4KFlB2UZc/sbskoKtEuLhlemPWHvn3wxrEttc3+gLrs4NZW6X9WEKaX44nT3YbBCa3nB2nMjbyVEoNzWZn0IHFpwmLYhr1WkbTu2/3hdia0UUESJ8EIff2e6Z9S8JioJ5P6fJUQOiNceliCp3tsyNYgvCKzn0Hua0808wwxMRdwCsDc5PCmzf3e6UjXzyHYwaO9906gZDBtKaIZ7d9q5DG6VdzNW4MEZ01NAlc88JMVL9sg8Fs3LUFXl1U5cNO//vTm8J13iRKemZF1LBRh1KXe8+ZQtt7sLZ+BYcfOL7kUNS63HhvrxnuoT53c=
        file: "dist/Cyber-Essentials-at-Home.pkg"
        skip_cleanup: true

    - name: "Python (latest) on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip
        - choco install nsis
        - export PATH="/c/Program Files (x86)/NSIS:$PATH"
      script:
        - python -m pip install -r requirements_windows.txt
        - pyinstaller main.py -n "Cyber Essentials at Home" --add-data "scripts;scripts" --add-data "imgs;imgs" -w -i imgs/logo.ico
        - cd resources
        - makensis installer.nsi
        - powershell -Command Get-FileHash "C:\\Users\\travis\\build\\Mark-Turner0\\ceah-tool\\resources\\Cyber-Essentials-at-Home-Installer.exe" -Algorithm SHA256
      before_deploy:
        - git config --local user.name = "Mark Turner"
        - git config --local user.email = "mark.turner-7@postgrad.manchester.ac.uk"
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key:
          secure: CvaeWnw10kKCkTNHm9E208exwfn5S6pluVQ2yabWgTJo/wZdEFhx+nC5KbodetuNslwDafStDg2i8E7Yl2dtZgzRA83EWfzVlWzfqF4bYYyoF1kVpdhjPOVWIrqqymBqrOH4HIrGgEyzB67imh3WI27xEmY+q+u2sTIzXA4xzbai71wo1w1wVqSbag0+0j4CunhaoR175IssxtH3RPPHe9XKKY65HZMqJsgdWAAy/NvbKOSGAG35vkJTDB7ESQh3DNRNB0yWo1YkOOQKOkP6od+u/Gm60Nr3E7vPfxCMwE9h1wACi2vDLBtscROLSJdEf2tmhzliYK+H3aMpUGwiFOAXXJmrc4oQWDnlQQWndyFWqbuj4KFlB2UZc/sbskoKtEuLhlemPWHvn3wxrEttc3+gLrs4NZW6X9WEKaX44nT3YbBCa3nB2nMjbyVEoNzWZn0IHFpwmLYhr1WkbTu2/3hdia0UUESJ8EIff2e6Z9S8JioJ5P6fJUQOiNceliCp3tsyNYgvCKzn0Hua0808wwxMRdwCsDc5PCmzf3e6UjXzyHYwaO9906gZDBtKaIZ7d9q5DG6VdzNW4MEZ01NAlc88JMVL9sg8Fs3LUFXl1U5cNO//vTm8J13iRKemZF1LBRh1KXe8+ZQtt7sLZ+BYcfOL7kUNS63HhvrxnuoT53c=
        file: "C:\\Users\\travis\\build\\Mark-Turner0\\ceah-tool\\resources\\Cyber-Essentials-at-Home-Installer.exe"
        skip_cleanup: true

install:
- pip3 install --upgrade pip  # all three OSes agree about 'pip3'
- pip3 install pyinstaller
