language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:

    - name: "Python 3.x.x on macOS"
      os: osx
      osx_image: xcode12.5  # Python 3.x.x running on macOS 11.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      script:
        - pip3 install -r requirements_mac.txt
        - pyinstaller main.py -n "Cyber Essentials at Home" --add-data scripts:scripts --add-data imgs:imgs -w -i imgs/logo.ico --version-file 0.1 --osx-bundle-identifier uk.markturner.ceah-tool
        - chmod +x resources/postinstall
        - cd dist
        - rm -fr "Cyber Essentials at Home"
        - pkgbuild --identifier uk.markturner.ceah-tool --install-location /Applications --root ./ --component-plist ../resources/ceah-tool.plist --scripts ../resources --ownership preserve component.pkg
        - productbuild --distribution ../resources/distribution.xml "./Cyber Essentials at Home.pkg"

    - name: "Python (latest) on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip
        - choco install nsis
        - export PATH="/c/Program Files (x86)/NSIS:$PATH"
      script:
        - python -m pip install -r requirements_windows.txt
        - pyinstaller main.py -n "Cyber Essentials at Home" --add-data "scripts;scripts" --add-data "imgs;imgs" -w -i imgs/logo.ico
        - cd resources
        - makensis installer.nsi

install:
- pip3 install --upgrade pip  # all three OSes agree about 'pip3'
- pip3 install pyinstaller

script: pyinstaller --onefile main.py
