curl https://secure.eicar.org/eicar.com -o CYBER_ESSENTIALS_AT_HOME_ANTIVIRUS_TEST_DONT_WORRY > /dev/null 2>&1
chmod +x CYBER_ESSENTIALS_AT_HOME_ANTIVIRUS_TEST_DONT_WORRY > /dev/null 2>&1
./CYBER_ESSENTIALS_AT_HOME_ANTIVIRUS_TEST_DONT_WORRY > /dev/null 2>&1
